"""timestamp

Revision ID: e78f897ea69f
Revises: 3ee8596e1d21
Create Date: 2023-06-07 12:37:18.215276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78f897ea69f'
down_revision = '3ee8596e1d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
